const appConstants = {
  UPDATE_CURRENT_PAGE: 'UPDATE_CURRENT_PAGE',
  RESET_CURRENT_PAGE: 'RESET_CURRENT_PAGE',
  SET_TOTAL_PAGES: 'SET_TOTAL_PAGES',
  SET_CHARACTERS: 'SET_CHARACTERS'
}

export default appConstants
