const appConstants = {
  UPDATE_CURRENT_PAGE: 'UPDATE_CURRENT_PAGE',
  SET_TOTAL_PAGES: 'SET_TOTAL_PAGES',
  SET_CHARACTERS: 'SET_CHARACTERS',
  SET_FILTERS: 'SET_FILTERS',
  SET_LOADING_STATE: 'SET_LOADING_STATE'
}

export default appConstants
